name: Create Release with JAR

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Clona el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura Java (necesario para compilar el proyecto y generar el .jar)
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    # Compila el proyecto (usando Maven como ejemplo; ajusta si usas Gradle u otro sistema)
    - name: Build JAR with Maven
      run: mvn clean package

    # Verifica que el archivo .jar exista en la ruta especificada
    - name: Check JAR existence
      run: |
        if [ ! -f out/artifacts/Clans_jar/Clans.jar ]; then
          echo "Error: Clans.jar not found in out/artifacts/Clans_jar/"
          exit 1
        fi

    # Crea el release en GitHub
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    # Sube el .jar al release
    - name: Upload JAR
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: out/artifacts/Clans_jar/Clans.jar
        asset_name: Clans.jar
        asset_content_type: application/java-archive
